#ifndef CERTS_H
#define CERTS_H

// Example only.
// Real certs.h is generated by scripts/generate-headers.sh after aws/provision.sh.
// Do not manually maintain generated certs.h in git.

// Amazon Root CA certificate (PEM with escaped newlines).
static const char AWS_CERT_CA[] =
    "-----BEGIN CERTIFICATE-----\n"
    "REPLACE_WITH_AMAZON_ROOT_CA_1_CONTENT\n"
    "-----END CERTIFICATE-----\n";

// Device certificate from AWS IoT Core.
static const char AWS_CERT_CRT[] =
    "-----BEGIN CERTIFICATE-----\n"
    "REPLACE_WITH_DEVICE_CERTIFICATE_CONTENT\n"
    "-----END CERTIFICATE-----\n";

// Device private key from AWS IoT Core.
static const char AWS_CERT_PRIVATE[] =
    "-----BEGIN RSA PRIVATE KEY-----\n"
    "REPLACE_WITH_DEVICE_PRIVATE_KEY_CONTENT\n"
    "-----END RSA PRIVATE KEY-----\n";

#endif  // CERTS_H
