#ifndef CONFIG_H
#define CONFIG_H

// Example only.
// Real config.h is generated by scripts/generate-headers.sh from env vars.
// Do not manually maintain generated config.h in git.

// Wi-Fi credentials
#define WIFI_SSID "your-ssid"
#define WIFI_PASSWORD "your-password"

// AWS IoT endpoint and thing identity
#define AWS_IOT_ENDPOINT "xxxxxxxxxxxx-ats.iot.ap-southeast-2.amazonaws.com"
#define THING_NAME "esp32-c"

// Telemetry publish cadence
#define PUBLISH_INTERVAL_SEC 60

// SNTP/NTP server
#define NTP_SERVER "pool.ntp.org"

#if PUBLISH_INTERVAL_SEC < 10 || PUBLISH_INTERVAL_SEC > 3600
#error "PUBLISH_INTERVAL_SEC must be between 10 and 3600"
#endif

#endif  // CONFIG_H
