#!/usr/bin/env bash
# Generate firmware/include/config.h and certs.h from CLI env vars + provisioned PEM files.
set -euo pipefail

# Usage:
#   WIFI_SSID=... WIFI_PASSWORD=... THING_NAME=... ./scripts/generate-headers.sh
#
# Optional:
#   AWS_IOT_ENDPOINT=...     auto-fetched from AWS CLI if unset
#   PUBLISH_INTERVAL_SEC=60
#   NTP_SERVER=pool.ntp.org
#   CERT_DIR=firmware/certs

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INCLUDE_DIR="${ROOT}/firmware/include"

: "${WIFI_SSID:?Set WIFI_SSID}"
: "${WIFI_PASSWORD:?Set WIFI_PASSWORD}"
: "${THING_NAME:?Set THING_NAME}"

PUBLISH_INTERVAL_SEC="${PUBLISH_INTERVAL_SEC:-60}"
NTP_SERVER="${NTP_SERVER:-pool.ntp.org}"
CERT_DIR="${CERT_DIR:-${ROOT}/firmware/certs}"

if [[ -z "${AWS_IOT_ENDPOINT:-}" ]]; then
  echo "AWS_IOT_ENDPOINT not set — fetching from AWS CLI..."
  AWS_IOT_ENDPOINT="$(aws iot describe-endpoint --endpoint-type iot:Data-ATS --query endpointAddress --output text)"
fi

CA_PEM="${CERT_DIR}/AmazonRootCA1.pem"
CRT_PEM="${CERT_DIR}/${THING_NAME}.cert.pem"
KEY_PEM="${CERT_DIR}/${THING_NAME}.private.key"

for pem in "${CA_PEM}" "${CRT_PEM}" "${KEY_PEM}"; do
  if [[ ! -f "${pem}" ]]; then
    echo "Missing ${pem} — run aws/provision.sh first (THING_NAME=${THING_NAME})." >&2
    exit 1
  fi
done

escape_c_define() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "${s}"
}

write_pem_c_array() {
  local var_name="$1"
  local pem_file="$2"
  echo "static const char ${var_name}[] ="
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line//\\/\\\\}"
    line="${line//\"/\\\"}"
    printf '    "%s\\n"\n' "${line}"
  done < "${pem_file}"
  echo ";"
}

WIFI_SSID_ESC="$(escape_c_define "${WIFI_SSID}")"
WIFI_PASSWORD_ESC="$(escape_c_define "${WIFI_PASSWORD}")"
ENDPOINT_ESC="$(escape_c_define "${AWS_IOT_ENDPOINT}")"
THING_NAME_ESC="$(escape_c_define "${THING_NAME}")"
NTP_SERVER_ESC="$(escape_c_define "${NTP_SERVER}")"

mkdir -p "${INCLUDE_DIR}"

cat > "${INCLUDE_DIR}/config.h" <<EOF
#ifndef CONFIG_H
#define CONFIG_H

// Generated by scripts/generate-headers.sh — do not edit; re-run with updated env vars.

// Wi-Fi credentials
#define WIFI_SSID "${WIFI_SSID_ESC}"
#define WIFI_PASSWORD "${WIFI_PASSWORD_ESC}"

// AWS IoT endpoint and thing identity
#define AWS_IOT_ENDPOINT "${ENDPOINT_ESC}"
#define THING_NAME "${THING_NAME_ESC}"

// Telemetry publish cadence
#define PUBLISH_INTERVAL_SEC ${PUBLISH_INTERVAL_SEC}

// SNTP/NTP server
#define NTP_SERVER "${NTP_SERVER_ESC}"

#if PUBLISH_INTERVAL_SEC < 10 || PUBLISH_INTERVAL_SEC > 3600
#error "PUBLISH_INTERVAL_SEC must be between 10 and 3600"
#endif

#endif  // CONFIG_H
EOF

{
  cat <<EOF
#ifndef CERTS_H
#define CERTS_H

// Generated by scripts/generate-headers.sh — do not edit; re-run after aws/provision.sh.

EOF
  echo "// Amazon Root CA certificate (PEM with escaped newlines)."
  write_pem_c_array "AWS_CERT_CA" "${CA_PEM}"
  echo
  echo "// Device certificate from AWS IoT Core."
  write_pem_c_array "AWS_CERT_CRT" "${CRT_PEM}"
  echo
  echo "// Device private key from AWS IoT Core."
  write_pem_c_array "AWS_CERT_PRIVATE" "${KEY_PEM}"
  echo
  echo "#endif  // CERTS_H"
} > "${INCLUDE_DIR}/certs.h"

echo "Wrote ${INCLUDE_DIR}/config.h"
echo "Wrote ${INCLUDE_DIR}/certs.h"
echo "THING_NAME=${THING_NAME}"
echo "AWS_IOT_ENDPOINT=${AWS_IOT_ENDPOINT}"
